using System;
using System.Linq;

namespace GCSProgramacaoTV.Model.Classes
{
    public static class Htv
    {
        public static String[] ListaDeCanais()
        {
            return new string[]
            {
                "+ globosat",
                "a&e",
                "amc",
                "animal planet",
                "axn",
                "band rede",
                "band news",
                "band sports",
                "bbc world news",
                "bis hd",
                "bloomberg",                
                "canal brasil",
                "cartoon network",
                "cinemax",
                "cnn international",
                "cnt",
                "combate",
                "comedy central",
                "discovery channel",
                "discovery home & health",
                "discovery kids",
                "discovery hd theater",
                "discovery science",
                "discovery turbo",
                "disney channel",
                "disney junior",
                "e! entertainment television",
                "ei maxx",
                "espn",
                "espn +",
                "espn brasil",
                "esporte interativo",
                "fox",
                "fox life",
                "fox sports",
                "fox sports 2",
                "futura",
                "fx",                
                "globo - sp",
                "globo news",
                "gloob",
                "gnt",
                "h2",
                "hbo",
                "hbo 2",
                "hbo family",
                "hbo plus",
                "hbo plus *e",
                "hbo signature",
                "history channel",
                "investigação discovery",                
                "max",
                "max 2",
                "max prime",
                "megapix",
                "mtv",
                "multicultura",
                "multishow",
                "national geographic",
                "nat geo wild hd",
                "nba tv",
                "nbr",
                "nhk world",
                "nickelodeon",
                "nick jr.",
                "off hd",
                "parmount channel",
                "premiere 2",
                "premiere 3",
                "premiere 4",
                "premiere 5",
                "premiere 7",
                "premiere clubes",
                "record",
                "rede tv",
                "rede vida",
                "sbt",                
                "sony",
                "space",
                "sports +",
                "sportv",
                "sportv 2",
                "sportv 3",
                "sundance",
                "syfy",
                "tbs",
                "telecine action",
                "telecine cult",
                "telecine fun",
                "telecine pipoca",
                "telecine premium",
                "telecine touch",                
                "tlc",
                "tnt",
                "trutv",
                "tvt",
                "tv cultura",
                "tv escola",
                "tv gazeta",
                "tv justiça",
                "tv senado",
                "universal channel",
                "univesp",
                "viva",
                "warner channel"
            };
        }

        public static bool ECanalHtv(string nomeCanal)
        {
            return ListaDeCanais().Contains(nomeCanal.ToLower());
        }
    }
}
